Repository hansung-pocs/blog-android, pull requests merged in 2022-08, with the labels that each got.

#159 로컬에 세션 토큰 저장 시 암호화 하여 저장하도록 수정
  data/build.gradle
  data/src/main/java/com/pocs/data/di/LocalModule.kt
Labels: f: auth

#172 불안정한 테스트 수정
  presentation/src/androidTest/java/com/pocs/presentation/KeyboardHelper.kt
  presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
Labels: flaky

#178 게시글 카테고리 별로 요청하는 API 구현
  data/src/main/java/com/pocs/data/api/PostApi.kt
  data/src/main/java/com/pocs/data/mapper/PostFilterTypeMapper.kt
  data/src/main/java/com/pocs/data/model/post/PostListDto.kt
  data/src/main/java/com/pocs/data/paging/AdminPostByUserPagingSource.kt
  data/src/main/java/com/pocs/data/paging/AdminPostPagingSource.kt
  data/src/main/java/com/pocs/data/paging/PostPagingSource.kt
  data/src/main/java/com/pocs/data/repository/PostRepositoryImpl.kt
  data/src/main/java/com/pocs/data/source/PostRemoteDataSource.kt
  data/src/main/java/com/pocs/data/source/PostRemoteDataSourceImpl.kt
  domain/src/main/java/com/pocs/domain/model/post/PostCategory.kt
  presentation/src/main/java/com/pocs/presentation/extension/PostExt.kt
  presentation/src/main/java/com/pocs/presentation/view/home/post/PostFragment.kt
  test-library/src/main/java/com/pocs/test_library/fake/source/remote/FakePostRemoteDataSource.kt
Labels: API

#180 모든 API 요청에 세션 토큰 헤더 포함하도록 수정
  data/src/main/java/com/pocs/data/api/AuthApi.kt
  data/src/main/java/com/pocs/data/di/NetworkModule.kt
  data/src/main/java/com/pocs/data/source/AuthLocalDataSourceImpl.kt
Labels: API

#181 게시글 조회수 구현
  data/src/main/java/com/pocs/data/mapper/PostDetailMapper.kt
  data/src/main/java/com/pocs/data/mapper/PostMapper.kt
  data/src/main/java/com/pocs/data/model/post/PostDetailDto.kt
  data/src/main/java/com/pocs/data/model/post/PostDto.kt
  domain/src/main/java/com/pocs/domain/model/post/Post.kt
  domain/src/main/java/com/pocs/domain/model/post/PostDetail.kt
  domain/src/test/java/com/pocs/domain/CanDeletePostUseCaseTest.kt
  domain/src/test/java/com/pocs/domain/CanEditPostUseCaseTest.kt
  presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
  presentation/src/main/java/com/pocs/presentation/mapper/PostDetailMapper.kt
  presentation/src/main/java/com/pocs/presentation/model/post/item/PostDetailItemUiState.kt
  presentation/src/main/java/com/pocs/presentation/view/component/Comments.kt
  presentation/src/main/java/com/pocs/presentation/view/component/Label.kt
  presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
  presentation/src/main/res/values/strings.xml
  test-library/src/main/java/com/pocs/test_library/mock/Post.kt
Labels: API, UI

#185 헤더에 토큰 추가하는 로직 문제수정 및 토큰 헤더 중복추가 않도록 수정
  data/src/main/java/com/pocs/data/api/AuthApi.kt
  data/src/main/java/com/pocs/data/di/NetworkModule.kt
  data/src/main/java/com/pocs/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/pocs/data/source/AuthLocalDataSource.kt
  data/src/main/java/com/pocs/data/source/AuthLocalDataSourceImpl.kt
  data/src/main/java/com/pocs/data/source/AuthRemoteDataSource.kt
  data/src/main/java/com/pocs/data/source/AuthRemoteDataSourceImpl.kt
  test-library/src/main/java/com/pocs/test_library/fake/source/local/FakeAuthLocalDataSource.kt
  test-library/src/main/java/com/pocs/test_library/fake/source/remote/FakeAuthRemoteDataSource.kt
Labels: API

#183 페이지네이션 API 기능 구현
  data/src/main/java/com/pocs/data/api/AdminApi.kt
  data/src/main/java/com/pocs/data/api/PostApi.kt
  data/src/main/java/com/pocs/data/api/UserApi.kt
  data/src/main/java/com/pocs/data/model/post/PostListDto.kt
  data/src/main/java/com/pocs/data/paging/AdminPostByUserPagingSource.kt
  data/src/main/java/com/pocs/data/paging/AdminPostPagingSource.kt
  data/src/main/java/com/pocs/data/paging/AdminUserPagingSource.kt
  data/src/main/java/com/pocs/data/paging/PostPagingSource.kt
  data/src/main/java/com/pocs/data/paging/UserPagingSource.kt
  data/src/main/java/com/pocs/data/repository/AdminRepositoryImpl.kt
  data/src/main/java/com/pocs/data/repository/PostRepositoryImpl.kt
  data/src/main/java/com/pocs/data/repository/UserRepositoryImpl.kt
Labels: API

#184 PostDetailScreen에 스크롤하면 앱바에 제목이 보이는 기능 구현
  presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
  presentation/src/main/java/com/pocs/presentation/view/component/AppBar.kt
  presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
Labels: UI

#186 회원 이름 검색 기능 구현
  data/src/main/java/com/pocs/data/api/UserApi.kt
  data/src/main/java/com/pocs/data/paging/UserPagingSource.kt
  data/src/main/java/com/pocs/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/pocs/domain/repository/UserRepository.kt
  domain/src/main/java/com/pocs/domain/usecase/user/SearchUserUseCase.kt
  presentation/src/main/java/com/pocs/presentation/model/user/UserUiState.kt
  presentation/src/main/java/com/pocs/presentation/view/component/appbar/SearchAppBar.kt
  presentation/src/main/java/com/pocs/presentation/view/component/button/AppBarBackButton.kt
  presentation/src/main/java/com/pocs/presentation/view/component/textfield/SimpleTextField.kt
  presentation/src/main/java/com/pocs/presentation/view/user/UserActivity.kt
  presentation/src/main/java/com/pocs/presentation/view/user/UserFragment.kt
  presentation/src/main/java/com/pocs/presentation/view/user/UserViewModel.kt
  presentation/src/main/res/layout/activity_post_detail.xml
  presentation/src/main/res/layout/activity_user.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/test/java/com/pocs/presentation/UserViewModelTest.kt
  test-library/src/main/java/com/pocs/test_library/fake/FakeUserRepositoryImpl.kt
  test-library/src/main/java/com/pocs/test_library/paging/PostCallback.kt
Labels: API, UI

#189 게시글 상세 페이지에 마크다운 지원
  build.gradle
  presentation/build.gradle
  presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
  presentation/src/androidTest/java/com/pocs/presentation/PostEditScreenTest.kt
  presentation/src/main/java/com/pocs/presentation/extension/ContextExt.kt
  presentation/src/main/java/com/pocs/presentation/extension/NumExt.kt
  presentation/src/main/java/com/pocs/presentation/extension/ViewExt.kt
  presentation/src/main/java/com/pocs/presentation/model/post/BasePostEditUiState.kt
  presentation/src/main/java/com/pocs/presentation/model/post/PostCreateUiState.kt
  presentation/src/main/java/com/pocs/presentation/model/post/PostEditUiState.kt
  presentation/src/main/java/com/pocs/presentation/view/component/markdown/MarkdownText.kt
  presentation/src/main/java/com/pocs/presentation/view/component/markdown/MarkdownToolBar.kt
  presentation/src/main/java/com/pocs/presentation/view/post/adapter/PostAdapter.kt
  presentation/src/main/java/com/pocs/presentation/view/post/adapter/PostViewHolder.kt
  presentation/src/main/java/com/pocs/presentation/view/post/create/PostCreateViewModel.kt
  presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
  presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditScreen.kt
  presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditViewModel.kt
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/themes.xml
  presentation/src/test/java/com/pocs/presentation/MarkdownToolBarTest.kt
Labels: UI

#191 질문답변 게시글 상세조회 에러 수정
  data/src/main/java/com/pocs/data/mapper/PostWriterMapper.kt
  data/src/main/java/com/pocs/data/model/comment/CommentWriterDto.kt
  data/src/main/java/com/pocs/data/model/post/PostWriterDto.kt
  domain/src/main/java/com/pocs/domain/model/comment/CommentWriter.kt
  domain/src/main/java/com/pocs/domain/model/post/PostCategory.kt
  domain/src/main/java/com/pocs/domain/model/post/PostWriter.kt
  presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
  presentation/src/androidTest/java/com/pocs/presentation/PostFragmentTest.kt
  presentation/src/main/java/com/pocs/presentation/model/comment/item/CommentWriterUiState.kt
  presentation/src/main/java/com/pocs/presentation/model/post/item/PostWriterUiState.kt
  presentation/src/main/java/com/pocs/presentation/model/study/StudyUiState.kt
  presentation/src/main/java/com/pocs/presentation/view/component/Comments.kt
  presentation/src/main/java/com/pocs/presentation/view/component/markdown/MarkdownText.kt
  presentation/src/main/java/com/pocs/presentation/view/home/post/PostFragment.kt
  presentation/src/main/java/com/pocs/presentation/view/home/study/StudyFragment.kt
  presentation/src/main/java/com/pocs/presentation/view/home/study/StudyViewModel.kt
  presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: UI

#194 익명 회원이 공지사항 등을 열람할 수 있던 문제 해결
  presentation/src/androidTest/java/com/pocs/presentation/PostFragmentTest.kt
  presentation/src/main/java/com/pocs/presentation/mapper/PostMapper.kt
  presentation/src/main/java/com/pocs/presentation/model/post/item/PostItemUiState.kt
  presentation/src/main/java/com/pocs/presentation/view/home/post/PostFragment.kt
  presentation/src/main/java/com/pocs/presentation/view/home/post/PostViewModel.kt
  presentation/src/main/java/com/pocs/presentation/view/post/adapter/PostViewHolder.kt
  presentation/src/test/java/com/pocs/presentation/PostViewModelTest.kt
Labels: UI

#195 관리자로 로그인 했을 때 내 댓글이 아닌 댓글은 편집할 수 없도록 수정
  presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
  presentation/src/main/java/com/pocs/presentation/view/component/bottomsheet/OptionModalBottomSheet.kt
  presentation/src/main/java/com/pocs/presentation/view/component/bottomsheet/PocsModalBottomSheet.kt
  presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
Labels: UI

#197 홈화면에서 FAB가 안보일때 스낵바 위치 이상하던 문제 해결
  presentation/src/androidTest/java/com/pocs/presentation/HomeActivityTest.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/pocs/presentation/model/post/HomeUiState.kt
  presentation/src/main/java/com/pocs/presentation/view/home/HomeActivity.kt
  presentation/src/main/java/com/pocs/presentation/view/home/HomeViewModel.kt
  presentation/src/main/java/com/pocs/presentation/view/home/post/PostFragment.kt
  presentation/src/main/java/com/pocs/presentation/view/home/study/StudyFragment.kt
Labels: UI

#208 댓글 추가 후 댓글 입력 창에 이전에 입력했던 댓글 남아있던 버그 수정
  presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
  presentation/src/main/java/com/pocs/presentation/view/component/bottomsheet/CommentModalBottomSheet.kt
Labels: UI

#209 익명 회원의 경우 유저 목록으로 이동하는 버튼 비활성화
  presentation/build.gradle
  presentation/src/androidTest/java/com/pocs/presentation/HomeActivityTest.kt
  presentation/src/androidTest/java/com/pocs/presentation/UserFragmentTest.kt
  presentation/src/main/java/com/pocs/presentation/model/post/HomeUiState.kt
  presentation/src/main/java/com/pocs/presentation/model/user/UserUiState.kt
  presentation/src/main/java/com/pocs/presentation/view/home/HomeActivity.kt
  presentation/src/main/java/com/pocs/presentation/view/home/HomeViewModel.kt
  presentation/src/main/java/com/pocs/presentation/view/user/UserFragment.kt
  presentation/src/main/res/values/strings.xml
  presentation/src/test/java/com/pocs/presentation/HomeViewModelTest.kt
Labels: UI

#207 비회원 계정 생성 페이지 UI수정
  presentation/src/main/java/com/pocs/presentation/view/user/anonymous/AnonymousCreateScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: UI

#211 익명 회원이 API응답으로 주어진 모든 게시글 열람 가능하도록 수정
  domain/src/main/java/com/pocs/domain/model/post/PostCategory.kt
  presentation/src/androidTest/java/com/pocs/presentation/HomeActivityTest.kt
  presentation/src/androidTest/java/com/pocs/presentation/UserFragmentTest.kt
  presentation/src/main/java/com/pocs/presentation/view/home/post/PostFragment.kt
  presentation/src/main/java/com/pocs/presentation/view/home/study/StudyFragment.kt
  presentation/src/main/res/values/strings.xml
Labels: UI

#212 익명회원은 본인이 작성한 QnA 게시글 외에는 댓글 작성할 수 없도록 수정
  presentation/src/androidTest/java/com/pocs/presentation/PostDetailActivityTest.kt
  presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
  presentation/src/androidTest/java/com/pocs/presentation/comment/CommentTest.kt
  presentation/src/main/java/com/pocs/presentation/model/comment/CommentsUiState.kt
  presentation/src/main/java/com/pocs/presentation/view/component/Comments.kt
  presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
  presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: UI

#210 게시글 상세조회 모델들(entity, dto, uiState)에 `onlyMember` 추가 및 API 대응
  data/src/main/java/com/pocs/data/mapper/PostDetailMapper.kt
  data/src/main/java/com/pocs/data/mapper/PostMapper.kt
  data/src/main/java/com/pocs/data/model/post/PostAddBody.kt
  data/src/main/java/com/pocs/data/model/post/PostDetailDto.kt
  data/src/main/java/com/pocs/data/model/post/PostDto.kt
  data/src/main/java/com/pocs/data/model/post/PostUpdateBody.kt
  data/src/main/java/com/pocs/data/repository/PostRepositoryImpl.kt
  domain/src/main/java/com/pocs/domain/model/post/Post.kt
  domain/src/main/java/com/pocs/domain/model/post/PostDetail.kt
  domain/src/main/java/com/pocs/domain/repository/PostRepository.kt
  domain/src/main/java/com/pocs/domain/usecase/post/AddPostUseCase.kt
  domain/src/main/java/com/pocs/domain/usecase/post/UpdatePostUseCase.kt
  domain/src/test/java/com/pocs/domain/CanDeletePostUseCaseTest.kt
  domain/src/test/java/com/pocs/domain/CanEditPostUseCaseTest.kt
  presentation/src/androidTest/java/com/pocs/presentation/PostEditActivityTest.kt
  presentation/src/androidTest/java/com/pocs/presentation/PostEditScreenTest.kt
  presentation/src/main/java/com/pocs/presentation/mapper/PostDetailMapper.kt
  presentation/src/main/java/com/pocs/presentation/model/post/BasePostEditUiState.kt
  presentation/src/main/java/com/pocs/presentation/model/post/PostCreateUiState.kt
  presentation/src/main/java/com/pocs/presentation/model/post/PostEditUiState.kt
  presentation/src/main/java/com/pocs/presentation/model/post/item/PostDetailItemUiState.kt
  presentation/src/main/java/com/pocs/presentation/view/component/checkbox/LabeledCheckBox.kt
  presentation/src/main/java/com/pocs/presentation/view/post/create/PostCreateViewModel.kt
  presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailActivity.kt
  presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
  presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditActivity.kt
  presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditScreen.kt
  presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditViewModel.kt
  presentation/src/main/res/values/strings.xml
  presentation/src/test/java/com/pocs/presentation/PostCreateViewModelTest.kt
  presentation/src/test/java/com/pocs/presentation/PostEditViewModelTest.kt
  test-library/src/main/java/com/pocs/test_library/fake/FakePostRepositoryImpl.kt
  test-library/src/main/java/com/pocs/test_library/mock/Post.kt
Labels: API

#214 회원 전용 게시글에는 PostDetailScreen에 "회원 전용" 문구 보이도록 수정
  presentation/src/androidTest/java/com/pocs/presentation/PostDetailScreenTest.kt
  presentation/src/main/java/com/pocs/presentation/view/post/detail/PostDetailScreen.kt
Labels: UI

#225 익명 회원일때 게시글 편집화면의 Chips 안보이도록 수정
  presentation/src/androidTest/java/com/pocs/presentation/PostEditScreenTest.kt
  presentation/src/main/java/com/pocs/presentation/model/post/BasePostEditUiState.kt
  presentation/src/main/java/com/pocs/presentation/view/component/Chips.kt
  presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditScreen.kt
Labels: UI

#224 유저 강퇴 후 회원 목록 화면에서 그대로 남아있던 문제 해결
  presentation/src/androidTest/java/com/pocs/presentation/UserDetailActivityTest.kt
  presentation/src/androidTest/java/com/pocs/presentation/UserDetailScreenTest.kt
  presentation/src/main/java/com/pocs/presentation/model/user/UserDetailUiState.kt
  presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailActivity.kt
  presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailScreen.kt
  presentation/src/main/java/com/pocs/presentation/view/user/detail/UserDetailViewModel.kt
Labels: UI

#226 PostEditScreen에서 Body 부분 전체 스크롤 가능하도록 수정
  presentation/src/main/java/com/pocs/presentation/view/post/edit/PostEditScreen.kt
Labels: UI

#230 불안정한 AdminUserFragment 테스트 수정
  presentation/src/androidTest/java/com/pocs/presentation/AdminUserFragmentTest.kt
  presentation/src/main/java/com/pocs/presentation/view/user/UserViewHolder.kt
Labels: flaky

#232 로그인 화면 UI 개선
  presentation/src/androidTest/java/com/pocs/presentation/LoginScreenTest.kt
  presentation/src/main/java/com/pocs/presentation/view/login/LoginActivity.kt
  presentation/src/main/java/com/pocs/presentation/view/login/LoginScreen.kt
  presentation/src/main/java/com/pocs/presentation/view/user/anonymous/AnonymousCreateScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: UI
